import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../../../../core/providers/auth_provider.dart';
import '../../../../../core/services/teknisi_service.dart';
import '../../../widgets/admin_components.dart';

/// Full-page Add Teknisi form (not a dialog/card)
class AddTeknisiPage extends StatefulWidget {
  const AddTeknisiPage({super.key});

  @override
  State<AddTeknisiPage> createState() => _AddTeknisiPageState();
}

class _AddTeknisiPageState extends State<AddTeknisiPage> {
  final _nameController = TextEditingController();
  final _emailController = TextEditingController();
  final _passwordController = TextEditingController();
  final _phoneController = TextEditingController();
  final _alamatController = TextEditingController();
  final _areaController = TextEditingController();

  final List<String> _roles = ['teknisi', 'admin'];
  String _selectedRole = 'teknisi';
  bool _isLoading = false;
  String? _errorMessage;
  bool _passwordAutoGenerated = false;

  String? _validateEmail(String? v) {
    if (v == null || v.trim().isEmpty) return 'Wajib diisi';
    final emailRegex = RegExp(r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$');
    if (!emailRegex.hasMatch(v.trim())) return 'Email tidak valid';
    return null;
  }

  @override
  void dispose() {
    _nameController.dispose();
    _emailController.dispose();
    _passwordController.dispose();
    _phoneController.dispose();
    _alamatController.dispose();
    _areaController.dispose();
    super.dispose();
  }

  void _generatePassword() {
    final chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#\$%^&*';
    final random = List.generate(12, (index) => chars[DateTime.now().millisecond % chars.length]).join();
    setState(() {
      _passwordController.text = random;
      _passwordAutoGenerated = true;
    });
  }

  void _copyPassword() {
    if (_passwordController.text.isNotEmpty) {
      // Note: Clipboard functionality would require additional setup
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Password disalin ke clipboard')),
      );
    }
  }

  Future<void> _submit() async {
    setState(() {
      _errorMessage = null;
    });

    // Validate required fields
    if (_nameController.text.trim().isEmpty) {
      _showError('Nama wajib diisi');
      return;
    }
    if (_emailController.text.trim().isEmpty) {
      _showError('Email wajib diisi');
      return;
    }
    if (_passwordController.text.isEmpty) {
      _showError('Password wajib diisi');
      return;
    }

    setState(() => _isLoading = true);

    try {
      final authProvider = Provider.of<AuthProvider>(context, listen: false);
      final teknisiService = TeknisiService(authProvider.token!);

      await teknisiService.createTeknisi({
        'name': _nameController.text.trim(),
        'email': _emailController.text.trim().toLowerCase(),
        'password': _passwordController.text,
        'phone': _phoneController.text.trim(),
        'alamat': _alamatController.text.trim(),
        'area_kerja': _areaController.text.trim(),
        'roles': [_selectedRole], // Backend mengharapkan array
      });

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Teknisi berhasil ditambahkan!'),
            backgroundColor: Colors.green,
          ),
        );
        Navigator.of(context).pop(true);
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _errorMessage = e.toString().replaceFirst('Exception: ', '');
        });
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  void _showError(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: Colors.red,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      backgroundColor: kBg,
      appBar: AppBar(
        title: const Text('Tambah Teknisi', style: TextStyle(color: kTextPrimary)),
        centerTitle: true,
        backgroundColor: Colors.white,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: kTextPrimary),
          onPressed: () => Navigator.of(context).pop(),
        ),
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Header Card
              Container(
                width: double.infinity,
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  gradient: const LinearGradient(
                    colors: [kIndigo, Color.fromARGB(255, 129, 140, 248)],
                    begin: Alignment.topLeft,
                    end: Alignment.bottomRight,
                  ),
                  borderRadius: BorderRadius.circular(16),
                ),
                child: Row(
                  children: [
                    Container(
                      width: 48,
                      height: 48,
                      decoration: BoxDecoration(
                        color: Colors.white.withValues(alpha: 0.2),
                        borderRadius: BorderRadius.circular(12),
                      ),
                      child: const Icon(Icons.person_add, color: Colors.white, size: 24),
                    ),
                    const SizedBox(width: 16),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            'Formulir Teknisi Baru',
                            style: theme.textTheme.titleMedium?.copyWith(
                              color: Colors.white,
                              fontWeight: FontWeight.w700,
                            ),
                          ),
                          const SizedBox(height: 4),
                          Text(
                            'Lengkapi data teknisi baru di bawah ini',
                            style: theme.textTheme.bodySmall?.copyWith(
                              color: Colors.white.withValues(alpha: 0.8),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),

              const SizedBox(height: 16),

              // Warning for admin
              if (_selectedRole == 'admin')
                Container(
                  width: double.infinity,
                  padding: const EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: kAmber.withValues(alpha: 0.1),
                    borderRadius: BorderRadius.circular(10),
                    border: Border.all(color: kAmber.withValues(alpha: 0.3)),
                  ),
                  child: Row(
                    children: [
                      Icon(Icons.warning_amber, color: kAmber, size: 20),
                      const SizedBox(width: 10),
                      Expanded(
                        child: Text(
                          'Peringatan: Admin memiliki akses penuh ke sistem',
                          style: TextStyle(
                            color: kAmber,
                            fontSize: 12,
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),

              const SizedBox(height: 16),

              // Error Message
              if (_errorMessage != null)
                Container(
                  width: double.infinity,
                  padding: const EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: kRose.withValues(alpha: 0.1),
                    borderRadius: BorderRadius.circular(10),
                    border: Border.all(color: kRose.withValues(alpha: 0.3)),
                  ),
                  child: Row(
                    children: [
                      Icon(Icons.error, color: kRose, size: 20),
                      const SizedBox(width: 10),
                      Expanded(
                        child: Text(
                          _errorMessage!,
                          style: TextStyle(
                            color: kRose,
                            fontSize: 12,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),

              const SizedBox(height: 16),

              // Form Fields
              _buildSectionTitle('Data Pribadi'),
              const SizedBox(height: 8),

              _buildField('Nama Lengkap', _nameController, Icons.person, TextInputType.name),
              const SizedBox(height: 8),
              _buildField('Email', _emailController, Icons.email, TextInputType.emailAddress, _validateEmail),
              const SizedBox(height: 8),
              _buildField('Nomor Telepon', _phoneController, Icons.phone, TextInputType.phone),
              const SizedBox(height: 8),
              _buildField('Alamat', _alamatController, Icons.home, TextInputType.streetAddress, null, 3),

              const SizedBox(height: 16),
              _buildSectionTitle('Informasi Kerja'),
              const SizedBox(height: 8),

              _buildField('Area Kerja', _areaController, Icons.location_on, TextInputType.text),
              const SizedBox(height: 8),

              // Role Selection
              Container(
                width: double.infinity,
                padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(10),
                  border: Border.all(color: kIndigo.withValues(alpha: 0.2)),
                ),
                child: DropdownButtonFormField<String>(
                  initialValue: _selectedRole,
                  decoration: const InputDecoration(
                    labelText: 'Role',
                    border: InputBorder.none,
                    prefixIcon: Icon(Icons.security, color: kIndigo),
                  ),
                  items: _roles.map((role) {
                    return DropdownMenuItem(
                      value: role,
                      child: Text(
                        role[0].toUpperCase() + role.substring(1),
                        style: const TextStyle(fontSize: 13),
                      ),
                    );
                  }).toList(),
                  onChanged: (value) {
                    setState(() {
                      _selectedRole = value ?? 'teknisi';
                    });
                  },
                ),
              ),

              const SizedBox(height: 16),
              _buildSectionTitle('Password'),
              const SizedBox(height: 8),

              // Password Field with Generate Button
              Container(
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(10),
                  border: Border.all(color: kIndigo.withValues(alpha: 0.2)),
                ),
                child: Row(
                  children: [
                    Expanded(
                      child: TextFormField(
                        controller: _passwordController,
                        obscureText: true,
                        style: const TextStyle(color: Colors.black),
                        decoration: InputDecoration(
                          labelText: 'Password',
                          border: InputBorder.none,
                          prefixIcon: Icon(Icons.lock, color: kIndigo),
                          contentPadding: EdgeInsets.symmetric(vertical: 12, horizontal: 16),
                          labelStyle: TextStyle(color: Colors.grey[600]),
                        ),
                      ),
                    ),
                    TextButton.icon(
                      onPressed: _generatePassword,
                      icon: const Icon(Icons.autorenew, size: 18),
                      label: const Text('Generate', style: TextStyle(fontSize: 12)),
                    ),
                    if (_passwordAutoGenerated)
                      TextButton.icon(
                        onPressed: _copyPassword,
                        icon: const Icon(Icons.copy, size: 18),
                        label: const Text('Copy', style: TextStyle(fontSize: 12)),
                      ),
                    const SizedBox(width: 8),
                  ],
                ),
              ),

              const SizedBox(height: 24),

              // Buttons
              Row(
                children: [
                  Expanded(
                    child: OutlinedButton(
                      onPressed: _isLoading ? null : () => Navigator.of(context).pop(),
                      style: OutlinedButton.styleFrom(
                        padding: const EdgeInsets.symmetric(vertical: 14),
                        side: BorderSide(color: kIndigo.withValues(alpha: 0.5)),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(10),
                        ),
                      ),
                      child: const Text('Batal', style: TextStyle(color: kIndigo)),
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: ElevatedButton(
                      onPressed: _isLoading ? null : _submit,
                      style: ElevatedButton.styleFrom(
                        backgroundColor: kIndigo,
                        padding: const EdgeInsets.symmetric(vertical: 14),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(10),
                        ),
                        elevation: 2,
                      ),
                      child: _isLoading
                          ? const SizedBox(
                              width: 20,
                              height: 20,
                              child: CircularProgressIndicator(
                                strokeWidth: 2,
                                color: Colors.white,
                              ),
                            )
                          : const Text(
                              'Simpan',
                              style: TextStyle(
                                color: Colors.white,
                                fontWeight: FontWeight.w600,
                              ),
                            ),
                    ),
                  ),
                ],
              ),

              const SizedBox(height: 20),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildSectionTitle(String title) {
    return Padding(
      padding: const EdgeInsets.only(left: 4),
      child: Text(
        title,
        style: const TextStyle(
          fontSize: 12,
          fontWeight: FontWeight.w700,
          color: kIndigo,
          letterSpacing: 0.5,
        ),
      ),
    );
  }

  Widget _buildField(
    String label,
    TextEditingController ctrl,
    IconData icon,
    TextInputType type, [
    String? Function(String?)? validator,
    int minLines = 1,
  ]) {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(10),
        border: Border.all(color: kIndigo.withValues(alpha: 0.2)),
      ),
      child: TextFormField(
        controller: ctrl,
        keyboardType: type,
        minLines: minLines,
        maxLines: minLines,
        style: const TextStyle(color: Colors.black),
        validator: validator,
        decoration: InputDecoration(
          labelText: label,
          border: InputBorder.none,
          prefixIcon: Icon(icon, color: kIndigo),
          contentPadding: EdgeInsets.symmetric(vertical: 12, horizontal: 16),
          labelStyle: TextStyle(color: Colors.grey[600]),
        ),
      ),
    );
  }
}

